### PR TITLE
Update yavijava to 6.0.05 [JENKINS-43962]

### PR DESCRIPTION
**Pull request by jordancoll**

### CODE REVIEW

**Comment by jordancoll** [comment]
@jswager @elordahl Any chance you could take a look at this please?

**Comment by jordancoll** [comment]
@elordahl the two big fixes are yavijava/yavijava#179 and yavijava/yavijava#171 

haven't performed any regression tests, I don't have a setup to test on.

**Comment by elordahl** [comment]
I'm in the same boat---I no longer have the resources to actively test these PRs.

Do you know if this issue was encountered in this plugin?  The upgrade seems pretty minor, so you have my 👍 to merge

**Comment by jordancoll** [comment]
Yeah, I personally run revert operations concurrently in pipeline jobs and reproduce yavijava/yavijava#171 quite often. Donno about the second issue.

**Comment by pjdarton** [comment]
I have resources to "passively test" these PRs...
If we can get all the PRs that I've requested merged into the head, plus any others we want (like this one), I can then try out the resulting xxx-SNAPSHOT plugin and see if it works on my build environment.
I can't guarantee that every aspect will get exercised/tested, but it'll make a reasonable "smoke test", e.g. if changing yavijava breaks things then I'll let you know :-)

**Comment by elordahl** [comment]
i dont have merge perms. @jswager can assist w/ this.

**Pull request merged**
