### PR TITLE
Enable  specify host in clone

### PR DESCRIPTION
**Pull request by Ichai5**
Hi jenkins Vsphere cloud Team,

I need the possibility to specify the host when cloning VM like requested in JENKINS-28870.
Please review the changeset and add it to the next release if the changes are acceptable.

Thanks in advance,

Ichai

### CODE REVIEW

**Comment by jswager** [comment]
@lchai5 - Pull Request can't be merged due to conflicts.  If you can correct, that would be appreciated.

**Comment by jswager** [comment]
@lchai5 - Pull Request can't be merged due to conflicts.  If you can correct, that would be appreciated.

**Comment by Ichai5** [comment]
Hi Jason,

How can  I see the merge problem ?
When I try to insert the changeset locally in a copy of trunk I get not errors.
Can you please specify which changeset and How can I see the problems ?

Thanks in advance,
Ichai

**Comment by jswager** [comment]
@Ichai5 - GitHub shows a command that will merge your code with the latest master code.

git checkout -b Ichai5-enable--specify-host-in-clone master
git pull https://github.com/Ichai5/vsphere-cloud-plugin.git enable--specify-host-in-clone
git checkout master
git merge --no-ff Ichai5-enable--specify-host-in-clone
git push origin master

**Comment by jswager** [comment]
This open PR hasn't been dealt with for the past month because it will not merge.  @Ichai5 I will close this PR in the next couple weeks if is not fixed up to merge properly.

**Comment by jswager** [comment]
Closing this pull request.  I greatly appreciate that folks are willing to contribute code, but the contribution needs to be completely handled.  If the merge issues can be resolved, then please feel free to re-open the pull request with the updates.

**Pull request closed without merging**
